# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1138, 759)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_controls = QtWidgets.QVBoxLayout()
        self.verticalLayout_controls.setObjectName("verticalLayout_controls")
        self.verticalLayout_root = QtWidgets.QVBoxLayout()
        self.verticalLayout_root.setObjectName("verticalLayout_root")
        self.label_root = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_root.sizePolicy().hasHeightForWidth())
        self.label_root.setSizePolicy(sizePolicy)
        self.label_root.setObjectName("label_root")
        self.verticalLayout_root.addWidget(self.label_root)
        self.lineEdit_root = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_root.sizePolicy().hasHeightForWidth())
        self.lineEdit_root.setSizePolicy(sizePolicy)
        self.lineEdit_root.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit_root.setObjectName("lineEdit_root")
        self.verticalLayout_root.addWidget(self.lineEdit_root)
        self.verticalLayout_controls.addLayout(self.verticalLayout_root)
        self.verticalLayout_name = QtWidgets.QVBoxLayout()
        self.verticalLayout_name.setObjectName("verticalLayout_name")
        self.label_name = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_name.sizePolicy().hasHeightForWidth())
        self.label_name.setSizePolicy(sizePolicy)
        self.label_name.setObjectName("label_name")
        self.verticalLayout_name.addWidget(self.label_name)
        self.lineEdit_name = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_name.sizePolicy().hasHeightForWidth())
        self.lineEdit_name.setSizePolicy(sizePolicy)
        self.lineEdit_name.setMinimumSize(QtCore.QSize(250, 0))
        self.lineEdit_name.setObjectName("lineEdit_name")
        self.verticalLayout_name.addWidget(self.lineEdit_name)
        self.verticalLayout_controls.addLayout(self.verticalLayout_name)
        self.groupBox_mode = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_mode.setObjectName("groupBox_mode")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.groupBox_mode)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.radioButton_singlewarp = QtWidgets.QRadioButton(self.groupBox_mode)
        self.radioButton_singlewarp.setObjectName("radioButton_singlewarp")
        self.buttonGroup_mode = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_mode.setObjectName("buttonGroup_mode")
        self.buttonGroup_mode.addButton(self.radioButton_singlewarp)
        self.verticalLayout_3.addWidget(self.radioButton_singlewarp)
        self.radioButton_multiwarp = QtWidgets.QRadioButton(self.groupBox_mode)
        self.radioButton_multiwarp.setChecked(True)
        self.radioButton_multiwarp.setObjectName("radioButton_multiwarp")
        self.buttonGroup_mode.addButton(self.radioButton_multiwarp)
        self.verticalLayout_3.addWidget(self.radioButton_multiwarp)
        self.verticalLayout_controls.addWidget(self.groupBox_mode)
        self.verticalLayout_enc = QtWidgets.QVBoxLayout()
        self.verticalLayout_enc.setObjectName("verticalLayout_enc")
        self.groupBox_enc = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_enc.sizePolicy().hasHeightForWidth())
        self.groupBox_enc.setSizePolicy(sizePolicy)
        self.groupBox_enc.setObjectName("groupBox_enc")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox_enc)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.radioButton_epi = QtWidgets.QRadioButton(self.groupBox_enc)
        self.radioButton_epi.setChecked(True)
        self.radioButton_epi.setObjectName("radioButton_epi")
        self.buttonGroup_enc = QtWidgets.QButtonGroup(MainWindow)
        self.buttonGroup_enc.setObjectName("buttonGroup_enc")
        self.buttonGroup_enc.addButton(self.radioButton_epi)
        self.verticalLayout_2.addWidget(self.radioButton_epi)
        self.radioButton_epi_without_disp_stack = QtWidgets.QRadioButton(self.groupBox_enc)
        self.radioButton_epi_without_disp_stack.setObjectName("radioButton_epi_without_disp_stack")
        self.buttonGroup_enc.addButton(self.radioButton_epi_without_disp_stack)
        self.verticalLayout_2.addWidget(self.radioButton_epi_without_disp_stack)
        self.radioButton_fs179 = QtWidgets.QRadioButton(self.groupBox_enc)
        self.radioButton_fs179.setObjectName("radioButton_fs179")
        self.buttonGroup_enc.addButton(self.radioButton_fs179)
        self.verticalLayout_2.addWidget(self.radioButton_fs179)
        self.radioButton_fs175 = QtWidgets.QRadioButton(self.groupBox_enc)
        self.radioButton_fs175.setObjectName("radioButton_fs175")
        self.buttonGroup_enc.addButton(self.radioButton_fs175)
        self.verticalLayout_2.addWidget(self.radioButton_fs175)
        self.radioButton_stack = QtWidgets.QRadioButton(self.groupBox_enc)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.radioButton_stack.sizePolicy().hasHeightForWidth())
        self.radioButton_stack.setSizePolicy(sizePolicy)
        self.radioButton_stack.setObjectName("radioButton_stack")
        self.buttonGroup_enc.addButton(self.radioButton_stack)
        self.verticalLayout_2.addWidget(self.radioButton_stack)
        self.radioButton_mono = QtWidgets.QRadioButton(self.groupBox_enc)
        self.radioButton_mono.setObjectName("radioButton_mono")
        self.buttonGroup_enc.addButton(self.radioButton_mono)
        self.verticalLayout_2.addWidget(self.radioButton_mono)
        self.verticalLayout_enc.addWidget(self.groupBox_enc)
        self.verticalLayout_controls.addLayout(self.verticalLayout_enc)
        self.horizontalLayout_id = QtWidgets.QHBoxLayout()
        self.horizontalLayout_id.setObjectName("horizontalLayout_id")
        self.label_id = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_id.sizePolicy().hasHeightForWidth())
        self.label_id.setSizePolicy(sizePolicy)
        self.label_id.setObjectName("label_id")
        self.horizontalLayout_id.addWidget(self.label_id)
        self.label_curr_id = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_curr_id.sizePolicy().hasHeightForWidth())
        self.label_curr_id.setSizePolicy(sizePolicy)
        self.label_curr_id.setObjectName("label_curr_id")
        self.horizontalLayout_id.addWidget(self.label_curr_id)
        self.lineEdit_curr_id = QtWidgets.QLineEdit(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lineEdit_curr_id.sizePolicy().hasHeightForWidth())
        self.lineEdit_curr_id.setSizePolicy(sizePolicy)
        self.lineEdit_curr_id.setObjectName("lineEdit_curr_id")
        self.horizontalLayout_id.addWidget(self.lineEdit_curr_id)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_id.addItem(spacerItem)
        self.verticalLayout_controls.addLayout(self.horizontalLayout_id)
        self.verticalLayout_prevnext = QtWidgets.QVBoxLayout()
        self.verticalLayout_prevnext.setObjectName("verticalLayout_prevnext")
        self.pushButton_plot = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_plot.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_plot.setAutoDefault(True)
        self.pushButton_plot.setDefault(True)
        self.pushButton_plot.setObjectName("pushButton_plot")
        self.verticalLayout_prevnext.addWidget(self.pushButton_plot)
        self.pushButton_next = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_next.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_next.setAutoDefault(True)
        self.pushButton_next.setObjectName("pushButton_next")
        self.verticalLayout_prevnext.addWidget(self.pushButton_next)
        self.pushButton_prev = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_prev.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.pushButton_prev.setAutoDefault(True)
        self.pushButton_prev.setObjectName("pushButton_prev")
        self.verticalLayout_prevnext.addWidget(self.pushButton_prev)
        self.verticalLayout_controls.addLayout(self.verticalLayout_prevnext)
        self.label_ctrls = QtWidgets.QLabel(self.centralwidget)
        self.label_ctrls.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ctrls.setObjectName("label_ctrls")
        self.verticalLayout_controls.addWidget(self.label_ctrls)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scrollArea.sizePolicy().hasHeightForWidth())
        self.scrollArea.setSizePolicy(sizePolicy)
        self.scrollArea.setMinimumSize(QtCore.QSize(280, 0))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 264, 804))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")
        self.widget_ctrl_img_1 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_ctrl_img_1.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.widget_ctrl_img_1.setObjectName("widget_ctrl_img_1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.widget_ctrl_img_1)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_ctrl_img_1 = QtWidgets.QLabel(self.widget_ctrl_img_1)
        self.label_ctrl_img_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ctrl_img_1.setObjectName("label_ctrl_img_1")
        self.verticalLayout_7.addWidget(self.label_ctrl_img_1)
        self.horizontalLayout_ctrl_tgl_img_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ctrl_tgl_img_1.setObjectName("horizontalLayout_ctrl_tgl_img_1")
        self.checkBox_ctrl_static_img_1 = QtWidgets.QCheckBox(self.widget_ctrl_img_1)
        self.checkBox_ctrl_static_img_1.setChecked(True)
        self.checkBox_ctrl_static_img_1.setObjectName("checkBox_ctrl_static_img_1")
        self.horizontalLayout_ctrl_tgl_img_1.addWidget(self.checkBox_ctrl_static_img_1)
        self.checkBox_ctrl_grp_tgl_img_1 = QtWidgets.QCheckBox(self.widget_ctrl_img_1)
        self.checkBox_ctrl_grp_tgl_img_1.setEnabled(False)
        self.checkBox_ctrl_grp_tgl_img_1.setCheckable(True)
        self.checkBox_ctrl_grp_tgl_img_1.setObjectName("checkBox_ctrl_grp_tgl_img_1")
        self.horizontalLayout_ctrl_tgl_img_1.addWidget(self.checkBox_ctrl_grp_tgl_img_1)
        self.pushButton_ctrl_tgl_img_1 = QtWidgets.QPushButton(self.widget_ctrl_img_1)
        self.pushButton_ctrl_tgl_img_1.setEnabled(False)
        self.pushButton_ctrl_tgl_img_1.setObjectName("pushButton_ctrl_tgl_img_1")
        self.horizontalLayout_ctrl_tgl_img_1.addWidget(self.pushButton_ctrl_tgl_img_1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_ctrl_tgl_img_1)
        self.horizontalLayout_ctrl_frames_img_1 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ctrl_frames_img_1.setObjectName("horizontalLayout_ctrl_frames_img_1")
        self.verticalLayout_ctrl_frame1_img_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ctrl_frame1_img_1.setObjectName("verticalLayout_ctrl_frame1_img_1")
        self.label_ctrl_frame1_img_1 = QtWidgets.QLabel(self.widget_ctrl_img_1)
        self.label_ctrl_frame1_img_1.setObjectName("label_ctrl_frame1_img_1")
        self.verticalLayout_ctrl_frame1_img_1.addWidget(self.label_ctrl_frame1_img_1)
        self.comboBox_ctrl_frame1_img_1 = QtWidgets.QComboBox(self.widget_ctrl_img_1)
        self.comboBox_ctrl_frame1_img_1.setObjectName("comboBox_ctrl_frame1_img_1")
        self.verticalLayout_ctrl_frame1_img_1.addWidget(self.comboBox_ctrl_frame1_img_1)
        self.horizontalLayout_ctrl_frames_img_1.addLayout(self.verticalLayout_ctrl_frame1_img_1)
        self.verticalLayout_ctrl_frame2_img_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ctrl_frame2_img_1.setObjectName("verticalLayout_ctrl_frame2_img_1")
        self.label_ctrl_frame2_img_1 = QtWidgets.QLabel(self.widget_ctrl_img_1)
        self.label_ctrl_frame2_img_1.setObjectName("label_ctrl_frame2_img_1")
        self.verticalLayout_ctrl_frame2_img_1.addWidget(self.label_ctrl_frame2_img_1)
        self.comboBox_ctrl_frame2_img_1 = QtWidgets.QComboBox(self.widget_ctrl_img_1)
        self.comboBox_ctrl_frame2_img_1.setObjectName("comboBox_ctrl_frame2_img_1")
        self.verticalLayout_ctrl_frame2_img_1.addWidget(self.comboBox_ctrl_frame2_img_1)
        self.horizontalLayout_ctrl_frames_img_1.addLayout(self.verticalLayout_ctrl_frame2_img_1)
        self.verticalLayout_7.addLayout(self.horizontalLayout_ctrl_frames_img_1)
        self.verticalLayout.addWidget(self.widget_ctrl_img_1)
        self.widget_ctrl_img_2 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_ctrl_img_2.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.widget_ctrl_img_2.setObjectName("widget_ctrl_img_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.widget_ctrl_img_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_ctrl_img_2 = QtWidgets.QLabel(self.widget_ctrl_img_2)
        self.label_ctrl_img_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ctrl_img_2.setObjectName("label_ctrl_img_2")
        self.verticalLayout_8.addWidget(self.label_ctrl_img_2)
        self.horizontalLayout_ctrl_tgl_img_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ctrl_tgl_img_2.setObjectName("horizontalLayout_ctrl_tgl_img_2")
        self.checkBox_ctrl_static_img_2 = QtWidgets.QCheckBox(self.widget_ctrl_img_2)
        self.checkBox_ctrl_static_img_2.setChecked(True)
        self.checkBox_ctrl_static_img_2.setObjectName("checkBox_ctrl_static_img_2")
        self.horizontalLayout_ctrl_tgl_img_2.addWidget(self.checkBox_ctrl_static_img_2)
        self.checkBox_ctrl_grp_tgl_img_2 = QtWidgets.QCheckBox(self.widget_ctrl_img_2)
        self.checkBox_ctrl_grp_tgl_img_2.setEnabled(False)
        self.checkBox_ctrl_grp_tgl_img_2.setObjectName("checkBox_ctrl_grp_tgl_img_2")
        self.horizontalLayout_ctrl_tgl_img_2.addWidget(self.checkBox_ctrl_grp_tgl_img_2)
        self.pushButton_ctrl_tgl_img_2 = QtWidgets.QPushButton(self.widget_ctrl_img_2)
        self.pushButton_ctrl_tgl_img_2.setEnabled(False)
        self.pushButton_ctrl_tgl_img_2.setObjectName("pushButton_ctrl_tgl_img_2")
        self.horizontalLayout_ctrl_tgl_img_2.addWidget(self.pushButton_ctrl_tgl_img_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_ctrl_tgl_img_2)
        self.horizontalLayout_ctrl_frames_img_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ctrl_frames_img_2.setObjectName("horizontalLayout_ctrl_frames_img_2")
        self.verticalLayout_ctrl_frame1_img_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ctrl_frame1_img_2.setObjectName("verticalLayout_ctrl_frame1_img_2")
        self.label_ctrl_frame1_img_2 = QtWidgets.QLabel(self.widget_ctrl_img_2)
        self.label_ctrl_frame1_img_2.setObjectName("label_ctrl_frame1_img_2")
        self.verticalLayout_ctrl_frame1_img_2.addWidget(self.label_ctrl_frame1_img_2)
        self.comboBox_ctrl_frame1_img_2 = QtWidgets.QComboBox(self.widget_ctrl_img_2)
        self.comboBox_ctrl_frame1_img_2.setObjectName("comboBox_ctrl_frame1_img_2")
        self.verticalLayout_ctrl_frame1_img_2.addWidget(self.comboBox_ctrl_frame1_img_2)
        self.horizontalLayout_ctrl_frames_img_2.addLayout(self.verticalLayout_ctrl_frame1_img_2)
        self.verticalLayout_ctrl_frame2_img_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ctrl_frame2_img_2.setObjectName("verticalLayout_ctrl_frame2_img_2")
        self.label_ctrl_frame2_img_2 = QtWidgets.QLabel(self.widget_ctrl_img_2)
        self.label_ctrl_frame2_img_2.setObjectName("label_ctrl_frame2_img_2")
        self.verticalLayout_ctrl_frame2_img_2.addWidget(self.label_ctrl_frame2_img_2)
        self.comboBox_ctrl_frame2_img_2 = QtWidgets.QComboBox(self.widget_ctrl_img_2)
        self.comboBox_ctrl_frame2_img_2.setObjectName("comboBox_ctrl_frame2_img_2")
        self.verticalLayout_ctrl_frame2_img_2.addWidget(self.comboBox_ctrl_frame2_img_2)
        self.horizontalLayout_ctrl_frames_img_2.addLayout(self.verticalLayout_ctrl_frame2_img_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_ctrl_frames_img_2)
        self.verticalLayout.addWidget(self.widget_ctrl_img_2)
        self.widget_ctrl_img_3 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_ctrl_img_3.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.widget_ctrl_img_3.setObjectName("widget_ctrl_img_3")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.widget_ctrl_img_3)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_ctrl_img_3 = QtWidgets.QLabel(self.widget_ctrl_img_3)
        self.label_ctrl_img_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ctrl_img_3.setObjectName("label_ctrl_img_3")
        self.verticalLayout_9.addWidget(self.label_ctrl_img_3)
        self.horizontalLayout_ctrl_tgl_img_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ctrl_tgl_img_3.setObjectName("horizontalLayout_ctrl_tgl_img_3")
        self.checkBox_ctrl_static_img_3 = QtWidgets.QCheckBox(self.widget_ctrl_img_3)
        self.checkBox_ctrl_static_img_3.setChecked(True)
        self.checkBox_ctrl_static_img_3.setObjectName("checkBox_ctrl_static_img_3")
        self.horizontalLayout_ctrl_tgl_img_3.addWidget(self.checkBox_ctrl_static_img_3)
        self.checkBox_ctrl_grp_tgl_img_3 = QtWidgets.QCheckBox(self.widget_ctrl_img_3)
        self.checkBox_ctrl_grp_tgl_img_3.setEnabled(False)
        self.checkBox_ctrl_grp_tgl_img_3.setObjectName("checkBox_ctrl_grp_tgl_img_3")
        self.horizontalLayout_ctrl_tgl_img_3.addWidget(self.checkBox_ctrl_grp_tgl_img_3)
        self.pushButton_ctrl_tgl_img_3 = QtWidgets.QPushButton(self.widget_ctrl_img_3)
        self.pushButton_ctrl_tgl_img_3.setEnabled(False)
        self.pushButton_ctrl_tgl_img_3.setObjectName("pushButton_ctrl_tgl_img_3")
        self.horizontalLayout_ctrl_tgl_img_3.addWidget(self.pushButton_ctrl_tgl_img_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_ctrl_tgl_img_3)
        self.horizontalLayout_ctrl_frames_img_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ctrl_frames_img_3.setObjectName("horizontalLayout_ctrl_frames_img_3")
        self.verticalLayout_ctrl_frame1_img_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ctrl_frame1_img_3.setObjectName("verticalLayout_ctrl_frame1_img_3")
        self.label_ctrl_frame1_img_3 = QtWidgets.QLabel(self.widget_ctrl_img_3)
        self.label_ctrl_frame1_img_3.setObjectName("label_ctrl_frame1_img_3")
        self.verticalLayout_ctrl_frame1_img_3.addWidget(self.label_ctrl_frame1_img_3)
        self.comboBox_ctrl_frame1_img_3 = QtWidgets.QComboBox(self.widget_ctrl_img_3)
        self.comboBox_ctrl_frame1_img_3.setObjectName("comboBox_ctrl_frame1_img_3")
        self.verticalLayout_ctrl_frame1_img_3.addWidget(self.comboBox_ctrl_frame1_img_3)
        self.horizontalLayout_ctrl_frames_img_3.addLayout(self.verticalLayout_ctrl_frame1_img_3)
        self.verticalLayout_ctrl_frame2_img_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ctrl_frame2_img_3.setObjectName("verticalLayout_ctrl_frame2_img_3")
        self.label_ctrl_frame2_img_3 = QtWidgets.QLabel(self.widget_ctrl_img_3)
        self.label_ctrl_frame2_img_3.setObjectName("label_ctrl_frame2_img_3")
        self.verticalLayout_ctrl_frame2_img_3.addWidget(self.label_ctrl_frame2_img_3)
        self.comboBox_ctrl_frame2_img_3 = QtWidgets.QComboBox(self.widget_ctrl_img_3)
        self.comboBox_ctrl_frame2_img_3.setObjectName("comboBox_ctrl_frame2_img_3")
        self.verticalLayout_ctrl_frame2_img_3.addWidget(self.comboBox_ctrl_frame2_img_3)
        self.horizontalLayout_ctrl_frames_img_3.addLayout(self.verticalLayout_ctrl_frame2_img_3)
        self.verticalLayout_9.addLayout(self.horizontalLayout_ctrl_frames_img_3)
        self.verticalLayout.addWidget(self.widget_ctrl_img_3)
        self.widget_ctrl_img_4 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_ctrl_img_4.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.widget_ctrl_img_4.setObjectName("widget_ctrl_img_4")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.widget_ctrl_img_4)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.label_ctrl_img_4 = QtWidgets.QLabel(self.widget_ctrl_img_4)
        self.label_ctrl_img_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ctrl_img_4.setObjectName("label_ctrl_img_4")
        self.verticalLayout_10.addWidget(self.label_ctrl_img_4)
        self.horizontalLayout_ctrl_tgl_img_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ctrl_tgl_img_4.setObjectName("horizontalLayout_ctrl_tgl_img_4")
        self.checkBox_ctrl_static_img_4 = QtWidgets.QCheckBox(self.widget_ctrl_img_4)
        self.checkBox_ctrl_static_img_4.setChecked(True)
        self.checkBox_ctrl_static_img_4.setObjectName("checkBox_ctrl_static_img_4")
        self.horizontalLayout_ctrl_tgl_img_4.addWidget(self.checkBox_ctrl_static_img_4)
        self.checkBox_ctrl_grp_tgl_img_4 = QtWidgets.QCheckBox(self.widget_ctrl_img_4)
        self.checkBox_ctrl_grp_tgl_img_4.setEnabled(False)
        self.checkBox_ctrl_grp_tgl_img_4.setObjectName("checkBox_ctrl_grp_tgl_img_4")
        self.horizontalLayout_ctrl_tgl_img_4.addWidget(self.checkBox_ctrl_grp_tgl_img_4)
        self.pushButton_ctrl_tgl_img_4 = QtWidgets.QPushButton(self.widget_ctrl_img_4)
        self.pushButton_ctrl_tgl_img_4.setEnabled(False)
        self.pushButton_ctrl_tgl_img_4.setObjectName("pushButton_ctrl_tgl_img_4")
        self.horizontalLayout_ctrl_tgl_img_4.addWidget(self.pushButton_ctrl_tgl_img_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_ctrl_tgl_img_4)
        self.horizontalLayout_ctrl_frames_img_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ctrl_frames_img_4.setObjectName("horizontalLayout_ctrl_frames_img_4")
        self.verticalLayout_ctrl_frame1_img_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ctrl_frame1_img_4.setObjectName("verticalLayout_ctrl_frame1_img_4")
        self.label_ctrl_frame1_img_4 = QtWidgets.QLabel(self.widget_ctrl_img_4)
        self.label_ctrl_frame1_img_4.setObjectName("label_ctrl_frame1_img_4")
        self.verticalLayout_ctrl_frame1_img_4.addWidget(self.label_ctrl_frame1_img_4)
        self.comboBox_ctrl_frame1_img_4 = QtWidgets.QComboBox(self.widget_ctrl_img_4)
        self.comboBox_ctrl_frame1_img_4.setObjectName("comboBox_ctrl_frame1_img_4")
        self.verticalLayout_ctrl_frame1_img_4.addWidget(self.comboBox_ctrl_frame1_img_4)
        self.horizontalLayout_ctrl_frames_img_4.addLayout(self.verticalLayout_ctrl_frame1_img_4)
        self.verticalLayout_ctrl_frame2_img_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ctrl_frame2_img_4.setObjectName("verticalLayout_ctrl_frame2_img_4")
        self.label_ctrl_frame2_img_4 = QtWidgets.QLabel(self.widget_ctrl_img_4)
        self.label_ctrl_frame2_img_4.setObjectName("label_ctrl_frame2_img_4")
        self.verticalLayout_ctrl_frame2_img_4.addWidget(self.label_ctrl_frame2_img_4)
        self.comboBox_ctrl_frame2_img_4 = QtWidgets.QComboBox(self.widget_ctrl_img_4)
        self.comboBox_ctrl_frame2_img_4.setObjectName("comboBox_ctrl_frame2_img_4")
        self.verticalLayout_ctrl_frame2_img_4.addWidget(self.comboBox_ctrl_frame2_img_4)
        self.horizontalLayout_ctrl_frames_img_4.addLayout(self.verticalLayout_ctrl_frame2_img_4)
        self.verticalLayout_10.addLayout(self.horizontalLayout_ctrl_frames_img_4)
        self.verticalLayout.addWidget(self.widget_ctrl_img_4)
        self.widget_ctrl_img_5 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_ctrl_img_5.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.widget_ctrl_img_5.setObjectName("widget_ctrl_img_5")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_ctrl_img_5)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.label_ctrl_img_5 = QtWidgets.QLabel(self.widget_ctrl_img_5)
        self.label_ctrl_img_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ctrl_img_5.setObjectName("label_ctrl_img_5")
        self.verticalLayout_11.addWidget(self.label_ctrl_img_5)
        self.horizontalLayout_ctrl_tgl_img_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ctrl_tgl_img_5.setObjectName("horizontalLayout_ctrl_tgl_img_5")
        self.checkBox_ctrl_static_img_5 = QtWidgets.QCheckBox(self.widget_ctrl_img_5)
        self.checkBox_ctrl_static_img_5.setChecked(True)
        self.checkBox_ctrl_static_img_5.setObjectName("checkBox_ctrl_static_img_5")
        self.horizontalLayout_ctrl_tgl_img_5.addWidget(self.checkBox_ctrl_static_img_5)
        self.checkBox_ctrl_grp_tgl_img_5 = QtWidgets.QCheckBox(self.widget_ctrl_img_5)
        self.checkBox_ctrl_grp_tgl_img_5.setEnabled(False)
        self.checkBox_ctrl_grp_tgl_img_5.setObjectName("checkBox_ctrl_grp_tgl_img_5")
        self.horizontalLayout_ctrl_tgl_img_5.addWidget(self.checkBox_ctrl_grp_tgl_img_5)
        self.pushButton_ctrl_tgl_img_5 = QtWidgets.QPushButton(self.widget_ctrl_img_5)
        self.pushButton_ctrl_tgl_img_5.setEnabled(False)
        self.pushButton_ctrl_tgl_img_5.setObjectName("pushButton_ctrl_tgl_img_5")
        self.horizontalLayout_ctrl_tgl_img_5.addWidget(self.pushButton_ctrl_tgl_img_5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_ctrl_tgl_img_5)
        self.horizontalLayout_ctrl_frames_img_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ctrl_frames_img_5.setObjectName("horizontalLayout_ctrl_frames_img_5")
        self.verticalLayout_ctrl_frame1_img_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ctrl_frame1_img_5.setObjectName("verticalLayout_ctrl_frame1_img_5")
        self.label_ctrl_frame1_img_5 = QtWidgets.QLabel(self.widget_ctrl_img_5)
        self.label_ctrl_frame1_img_5.setObjectName("label_ctrl_frame1_img_5")
        self.verticalLayout_ctrl_frame1_img_5.addWidget(self.label_ctrl_frame1_img_5)
        self.comboBox_ctrl_frame1_img_5 = QtWidgets.QComboBox(self.widget_ctrl_img_5)
        self.comboBox_ctrl_frame1_img_5.setObjectName("comboBox_ctrl_frame1_img_5")
        self.verticalLayout_ctrl_frame1_img_5.addWidget(self.comboBox_ctrl_frame1_img_5)
        self.horizontalLayout_ctrl_frames_img_5.addLayout(self.verticalLayout_ctrl_frame1_img_5)
        self.verticalLayout_ctrl_frame2_img_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ctrl_frame2_img_5.setObjectName("verticalLayout_ctrl_frame2_img_5")
        self.label_ctrl_frame2_img_5 = QtWidgets.QLabel(self.widget_ctrl_img_5)
        self.label_ctrl_frame2_img_5.setObjectName("label_ctrl_frame2_img_5")
        self.verticalLayout_ctrl_frame2_img_5.addWidget(self.label_ctrl_frame2_img_5)
        self.comboBox_ctrl_frame2_img_5 = QtWidgets.QComboBox(self.widget_ctrl_img_5)
        self.comboBox_ctrl_frame2_img_5.setObjectName("comboBox_ctrl_frame2_img_5")
        self.verticalLayout_ctrl_frame2_img_5.addWidget(self.comboBox_ctrl_frame2_img_5)
        self.horizontalLayout_ctrl_frames_img_5.addLayout(self.verticalLayout_ctrl_frame2_img_5)
        self.verticalLayout_11.addLayout(self.horizontalLayout_ctrl_frames_img_5)
        self.verticalLayout.addWidget(self.widget_ctrl_img_5)
        self.widget_ctrl_img_6 = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.widget_ctrl_img_6.setStyleSheet("background-color: rgb(186, 189, 182);")
        self.widget_ctrl_img_6.setObjectName("widget_ctrl_img_6")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget_ctrl_img_6)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_ctrl_img_6 = QtWidgets.QLabel(self.widget_ctrl_img_6)
        self.label_ctrl_img_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_ctrl_img_6.setObjectName("label_ctrl_img_6")
        self.verticalLayout_12.addWidget(self.label_ctrl_img_6)
        self.horizontalLayout_ctrl_tgl_img_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ctrl_tgl_img_6.setObjectName("horizontalLayout_ctrl_tgl_img_6")
        self.checkBox_ctrl_static_img_6 = QtWidgets.QCheckBox(self.widget_ctrl_img_6)
        self.checkBox_ctrl_static_img_6.setChecked(True)
        self.checkBox_ctrl_static_img_6.setObjectName("checkBox_ctrl_static_img_6")
        self.horizontalLayout_ctrl_tgl_img_6.addWidget(self.checkBox_ctrl_static_img_6)
        self.checkBox_ctrl_grp_tgl_img_6 = QtWidgets.QCheckBox(self.widget_ctrl_img_6)
        self.checkBox_ctrl_grp_tgl_img_6.setEnabled(False)
        self.checkBox_ctrl_grp_tgl_img_6.setObjectName("checkBox_ctrl_grp_tgl_img_6")
        self.horizontalLayout_ctrl_tgl_img_6.addWidget(self.checkBox_ctrl_grp_tgl_img_6)
        self.pushButton_ctrl_tgl_img_6 = QtWidgets.QPushButton(self.widget_ctrl_img_6)
        self.pushButton_ctrl_tgl_img_6.setEnabled(False)
        self.pushButton_ctrl_tgl_img_6.setObjectName("pushButton_ctrl_tgl_img_6")
        self.horizontalLayout_ctrl_tgl_img_6.addWidget(self.pushButton_ctrl_tgl_img_6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_ctrl_tgl_img_6)
        self.horizontalLayout_ctrl_frames_img_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_ctrl_frames_img_6.setObjectName("horizontalLayout_ctrl_frames_img_6")
        self.verticalLayout_ctrl_frame1_img_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ctrl_frame1_img_6.setObjectName("verticalLayout_ctrl_frame1_img_6")
        self.label_ctrl_frame1_img_6 = QtWidgets.QLabel(self.widget_ctrl_img_6)
        self.label_ctrl_frame1_img_6.setObjectName("label_ctrl_frame1_img_6")
        self.verticalLayout_ctrl_frame1_img_6.addWidget(self.label_ctrl_frame1_img_6)
        self.comboBox_ctrl_frame1_img_6 = QtWidgets.QComboBox(self.widget_ctrl_img_6)
        self.comboBox_ctrl_frame1_img_6.setObjectName("comboBox_ctrl_frame1_img_6")
        self.verticalLayout_ctrl_frame1_img_6.addWidget(self.comboBox_ctrl_frame1_img_6)
        self.horizontalLayout_ctrl_frames_img_6.addLayout(self.verticalLayout_ctrl_frame1_img_6)
        self.verticalLayout_ctrl_frame2_img_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_ctrl_frame2_img_6.setObjectName("verticalLayout_ctrl_frame2_img_6")
        self.label_ctrl_frame2_img_6 = QtWidgets.QLabel(self.widget_ctrl_img_6)
        self.label_ctrl_frame2_img_6.setObjectName("label_ctrl_frame2_img_6")
        self.verticalLayout_ctrl_frame2_img_6.addWidget(self.label_ctrl_frame2_img_6)
        self.comboBox_ctrl_frame2_img_6 = QtWidgets.QComboBox(self.widget_ctrl_img_6)
        self.comboBox_ctrl_frame2_img_6.setObjectName("comboBox_ctrl_frame2_img_6")
        self.verticalLayout_ctrl_frame2_img_6.addWidget(self.comboBox_ctrl_frame2_img_6)
        self.horizontalLayout_ctrl_frames_img_6.addLayout(self.verticalLayout_ctrl_frame2_img_6)
        self.verticalLayout_12.addLayout(self.horizontalLayout_ctrl_frames_img_6)
        self.verticalLayout.addWidget(self.widget_ctrl_img_6)
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.verticalLayout_controls.addWidget(self.scrollArea)
        self.pushButton_tgl_group = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_tgl_group.setObjectName("pushButton_tgl_group")
        self.verticalLayout_controls.addWidget(self.pushButton_tgl_group)
        self.horizontalLayout.addLayout(self.verticalLayout_controls)
        self.groupBox_plots = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_plots.sizePolicy().hasHeightForWidth())
        self.groupBox_plots.setSizePolicy(sizePolicy)
        self.groupBox_plots.setObjectName("groupBox_plots")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_plots)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.tabWidget = QtWidgets.QTabWidget(self.groupBox_plots)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_depth_disp = QtWidgets.QWidget()
        self.tab_depth_disp.setObjectName("tab_depth_disp")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.tab_depth_disp)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_img_tminus = QtWidgets.QVBoxLayout()
        self.verticalLayout_img_tminus.setObjectName("verticalLayout_img_tminus")
        self.label_img_tminus = QtWidgets.QLabel(self.tab_depth_disp)
        self.label_img_tminus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_tminus.setObjectName("label_img_tminus")
        self.verticalLayout_img_tminus.addWidget(self.label_img_tminus)
        self.widget_img_tminus = QtWidgets.QWidget(self.tab_depth_disp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_img_tminus.sizePolicy().hasHeightForWidth())
        self.widget_img_tminus.setSizePolicy(sizePolicy)
        self.widget_img_tminus.setObjectName("widget_img_tminus")
        self.verticalLayout_img_tminus.addWidget(self.widget_img_tminus)
        self.horizontalLayout_2.addLayout(self.verticalLayout_img_tminus)
        self.verticalLayout_img_t = QtWidgets.QVBoxLayout()
        self.verticalLayout_img_t.setObjectName("verticalLayout_img_t")
        self.label_img_t = QtWidgets.QLabel(self.tab_depth_disp)
        self.label_img_t.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_t.setObjectName("label_img_t")
        self.verticalLayout_img_t.addWidget(self.label_img_t)
        self.widget_img_t = QtWidgets.QWidget(self.tab_depth_disp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_img_t.sizePolicy().hasHeightForWidth())
        self.widget_img_t.setSizePolicy(sizePolicy)
        self.widget_img_t.setObjectName("widget_img_t")
        self.verticalLayout_img_t.addWidget(self.widget_img_t)
        self.horizontalLayout_2.addLayout(self.verticalLayout_img_t)
        self.verticalLayout_img_tplus = QtWidgets.QVBoxLayout()
        self.verticalLayout_img_tplus.setObjectName("verticalLayout_img_tplus")
        self.label_img_tplus = QtWidgets.QLabel(self.tab_depth_disp)
        self.label_img_tplus.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_tplus.setObjectName("label_img_tplus")
        self.verticalLayout_img_tplus.addWidget(self.label_img_tplus)
        self.widget_img_tplus = QtWidgets.QWidget(self.tab_depth_disp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_img_tplus.sizePolicy().hasHeightForWidth())
        self.widget_img_tplus.setSizePolicy(sizePolicy)
        self.widget_img_tplus.setObjectName("widget_img_tplus")
        self.verticalLayout_img_tplus.addWidget(self.widget_img_tplus)
        self.horizontalLayout_2.addLayout(self.verticalLayout_img_tplus)
        self.verticalLayout_5.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_disp_depth = QtWidgets.QHBoxLayout()
        self.horizontalLayout_disp_depth.setObjectName("horizontalLayout_disp_depth")
        self.verticalLayout_disp = QtWidgets.QVBoxLayout()
        self.verticalLayout_disp.setObjectName("verticalLayout_disp")
        self.label_disp = QtWidgets.QLabel(self.tab_depth_disp)
        self.label_disp.setAlignment(QtCore.Qt.AlignCenter)
        self.label_disp.setObjectName("label_disp")
        self.verticalLayout_disp.addWidget(self.label_disp)
        self.widget_disp_t = QtWidgets.QWidget(self.tab_depth_disp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_disp_t.sizePolicy().hasHeightForWidth())
        self.widget_disp_t.setSizePolicy(sizePolicy)
        self.widget_disp_t.setObjectName("widget_disp_t")
        self.verticalLayout_disp.addWidget(self.widget_disp_t)
        self.horizontalLayout_disp_depth.addLayout(self.verticalLayout_disp)
        self.verticalLayout_depth = QtWidgets.QVBoxLayout()
        self.verticalLayout_depth.setObjectName("verticalLayout_depth")
        self.label_depth = QtWidgets.QLabel(self.tab_depth_disp)
        self.label_depth.setAlignment(QtCore.Qt.AlignCenter)
        self.label_depth.setObjectName("label_depth")
        self.verticalLayout_depth.addWidget(self.label_depth)
        self.widget_depth_t = QtWidgets.QWidget(self.tab_depth_disp)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_depth_t.sizePolicy().hasHeightForWidth())
        self.widget_depth_t.setSizePolicy(sizePolicy)
        self.widget_depth_t.setObjectName("widget_depth_t")
        self.verticalLayout_depth.addWidget(self.widget_depth_t)
        self.horizontalLayout_disp_depth.addLayout(self.verticalLayout_depth)
        self.verticalLayout_5.addLayout(self.horizontalLayout_disp_depth)
        self.tabWidget.addTab(self.tab_depth_disp, "")
        self.tab_warps = QtWidgets.QWidget()
        self.tab_warps.setObjectName("tab_warps")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.tab_warps)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.horizontalLayout_warps = QtWidgets.QHBoxLayout()
        self.horizontalLayout_warps.setObjectName("horizontalLayout_warps")
        self.verticalLayout_img_1 = QtWidgets.QVBoxLayout()
        self.verticalLayout_img_1.setObjectName("verticalLayout_img_1")
        self.label_img_1 = QtWidgets.QLabel(self.tab_warps)
        self.label_img_1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_1.setObjectName("label_img_1")
        self.verticalLayout_img_1.addWidget(self.label_img_1)
        self.widget_img_1 = QtWidgets.QWidget(self.tab_warps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_img_1.sizePolicy().hasHeightForWidth())
        self.widget_img_1.setSizePolicy(sizePolicy)
        self.widget_img_1.setObjectName("widget_img_1")
        self.verticalLayout_img_1.addWidget(self.widget_img_1)
        self.horizontalLayout_warps.addLayout(self.verticalLayout_img_1)
        self.verticalLayout_img_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_img_2.setObjectName("verticalLayout_img_2")
        self.label_img_2 = QtWidgets.QLabel(self.tab_warps)
        self.label_img_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_2.setObjectName("label_img_2")
        self.verticalLayout_img_2.addWidget(self.label_img_2)
        self.widget_img_2 = QtWidgets.QWidget(self.tab_warps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_img_2.sizePolicy().hasHeightForWidth())
        self.widget_img_2.setSizePolicy(sizePolicy)
        self.widget_img_2.setObjectName("widget_img_2")
        self.verticalLayout_img_2.addWidget(self.widget_img_2)
        self.horizontalLayout_warps.addLayout(self.verticalLayout_img_2)
        self.verticalLayout_img_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_img_3.setObjectName("verticalLayout_img_3")
        self.label_img_3 = QtWidgets.QLabel(self.tab_warps)
        self.label_img_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_3.setObjectName("label_img_3")
        self.verticalLayout_img_3.addWidget(self.label_img_3)
        self.widget_img_3 = QtWidgets.QWidget(self.tab_warps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_img_3.sizePolicy().hasHeightForWidth())
        self.widget_img_3.setSizePolicy(sizePolicy)
        self.widget_img_3.setObjectName("widget_img_3")
        self.verticalLayout_img_3.addWidget(self.widget_img_3)
        self.horizontalLayout_warps.addLayout(self.verticalLayout_img_3)
        self.verticalLayout_6.addLayout(self.horizontalLayout_warps)
        self.horizontalLayout_warps2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_warps2.setObjectName("horizontalLayout_warps2")
        self.verticalLayout_img_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_img_4.setObjectName("verticalLayout_img_4")
        self.label_img_4 = QtWidgets.QLabel(self.tab_warps)
        self.label_img_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_4.setObjectName("label_img_4")
        self.verticalLayout_img_4.addWidget(self.label_img_4)
        self.widget_img_4 = QtWidgets.QWidget(self.tab_warps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_img_4.sizePolicy().hasHeightForWidth())
        self.widget_img_4.setSizePolicy(sizePolicy)
        self.widget_img_4.setObjectName("widget_img_4")
        self.verticalLayout_img_4.addWidget(self.widget_img_4)
        self.horizontalLayout_warps2.addLayout(self.verticalLayout_img_4)
        self.verticalLayout_img_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_img_5.setObjectName("verticalLayout_img_5")
        self.label_img_5 = QtWidgets.QLabel(self.tab_warps)
        self.label_img_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_5.setObjectName("label_img_5")
        self.verticalLayout_img_5.addWidget(self.label_img_5)
        self.widget_img_5 = QtWidgets.QWidget(self.tab_warps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_img_5.sizePolicy().hasHeightForWidth())
        self.widget_img_5.setSizePolicy(sizePolicy)
        self.widget_img_5.setObjectName("widget_img_5")
        self.verticalLayout_img_5.addWidget(self.widget_img_5)
        self.horizontalLayout_warps2.addLayout(self.verticalLayout_img_5)
        self.verticalLayout_img_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_img_6.setObjectName("verticalLayout_img_6")
        self.label_img_6 = QtWidgets.QLabel(self.tab_warps)
        self.label_img_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_img_6.setObjectName("label_img_6")
        self.verticalLayout_img_6.addWidget(self.label_img_6)
        self.widget_img_6 = QtWidgets.QWidget(self.tab_warps)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_img_6.sizePolicy().hasHeightForWidth())
        self.widget_img_6.setSizePolicy(sizePolicy)
        self.widget_img_6.setObjectName("widget_img_6")
        self.verticalLayout_img_6.addWidget(self.widget_img_6)
        self.horizontalLayout_warps2.addLayout(self.verticalLayout_img_6)
        self.verticalLayout_6.addLayout(self.horizontalLayout_warps2)
        self.tabWidget.addTab(self.tab_warps, "")
        self.verticalLayout_4.addWidget(self.tabWidget)
        self.horizontalLayout.addWidget(self.groupBox_plots)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1138, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Visualize Results"))
        self.label_root.setText(_translate("MainWindow", "Root Folder"))
        self.lineEdit_root.setStatusTip(_translate("MainWindow", "Enter the path of the root folder"))
        self.lineEdit_root.setWhatsThis(_translate("MainWindow", "Enter the path of the root folder"))
        self.label_name.setText(_translate("MainWindow", "Sequence Name"))
        self.lineEdit_name.setStatusTip(_translate("MainWindow", "Enter the name of the sequence"))
        self.lineEdit_name.setWhatsThis(_translate("MainWindow", "Enter the name of the sequence"))
        self.groupBox_mode.setTitle(_translate("MainWindow", "Mode"))
        self.radioButton_singlewarp.setText(_translate("MainWindow", "singlewarp"))
        self.radioButton_multiwarp.setText(_translate("MainWindow", "multiwarp-5"))
        self.groupBox_enc.setTitle(_translate("MainWindow", "Encoding"))
        self.radioButton_epi.setText(_translate("MainWindow", "epi"))
        self.radioButton_epi_without_disp_stack.setText(_translate("MainWindow", "epi_without_disp_stack"))
        self.radioButton_fs179.setText(_translate("MainWindow", "focalstack-17-9"))
        self.radioButton_fs175.setText(_translate("MainWindow", "focalstack-17-5"))
        self.radioButton_stack.setText(_translate("MainWindow", "stack"))
        self.radioButton_mono.setText(_translate("MainWindow", "monocular"))
        self.label_id.setText(_translate("MainWindow", "Image ID:"))
        self.label_curr_id.setText(_translate("MainWindow", "#"))
        self.pushButton_plot.setText(_translate("MainWindow", "Plot"))
        self.pushButton_next.setText(_translate("MainWindow", "Next"))
        self.pushButton_prev.setText(_translate("MainWindow", "Previous"))
        self.label_ctrls.setText(_translate("MainWindow", "Image Controls"))
        self.label_ctrl_img_1.setText(_translate("MainWindow", "Image 1"))
        self.checkBox_ctrl_static_img_1.setText(_translate("MainWindow", "Static"))
        self.checkBox_ctrl_grp_tgl_img_1.setText(_translate("MainWindow", "Group"))
        self.pushButton_ctrl_tgl_img_1.setText(_translate("MainWindow", "Toggle"))
        self.label_ctrl_frame1_img_1.setText(_translate("MainWindow", "Frame 1"))
        self.label_ctrl_frame2_img_1.setText(_translate("MainWindow", "Frame 2"))
        self.label_ctrl_img_2.setText(_translate("MainWindow", "Image 2"))
        self.checkBox_ctrl_static_img_2.setText(_translate("MainWindow", "Static"))
        self.checkBox_ctrl_grp_tgl_img_2.setText(_translate("MainWindow", "Group"))
        self.pushButton_ctrl_tgl_img_2.setText(_translate("MainWindow", "Toggle"))
        self.label_ctrl_frame1_img_2.setText(_translate("MainWindow", "Frame 1"))
        self.label_ctrl_frame2_img_2.setText(_translate("MainWindow", "Frame 2"))
        self.label_ctrl_img_3.setText(_translate("MainWindow", "Image 3"))
        self.checkBox_ctrl_static_img_3.setText(_translate("MainWindow", "Static"))
        self.checkBox_ctrl_grp_tgl_img_3.setText(_translate("MainWindow", "Group"))
        self.pushButton_ctrl_tgl_img_3.setText(_translate("MainWindow", "Toggle"))
        self.label_ctrl_frame1_img_3.setText(_translate("MainWindow", "Frame 1"))
        self.label_ctrl_frame2_img_3.setText(_translate("MainWindow", "Frame 2"))
        self.label_ctrl_img_4.setText(_translate("MainWindow", "Image 4"))
        self.checkBox_ctrl_static_img_4.setText(_translate("MainWindow", "Static"))
        self.checkBox_ctrl_grp_tgl_img_4.setText(_translate("MainWindow", "Group"))
        self.pushButton_ctrl_tgl_img_4.setText(_translate("MainWindow", "Toggle"))
        self.label_ctrl_frame1_img_4.setText(_translate("MainWindow", "Frame 1"))
        self.label_ctrl_frame2_img_4.setText(_translate("MainWindow", "Frame 2"))
        self.label_ctrl_img_5.setText(_translate("MainWindow", "Image 5"))
        self.checkBox_ctrl_static_img_5.setText(_translate("MainWindow", "Static"))
        self.checkBox_ctrl_grp_tgl_img_5.setText(_translate("MainWindow", "Group"))
        self.pushButton_ctrl_tgl_img_5.setText(_translate("MainWindow", "Toggle"))
        self.label_ctrl_frame1_img_5.setText(_translate("MainWindow", "Frame 1"))
        self.label_ctrl_frame2_img_5.setText(_translate("MainWindow", "Frame 2"))
        self.label_ctrl_img_6.setText(_translate("MainWindow", "Image 6"))
        self.checkBox_ctrl_static_img_6.setText(_translate("MainWindow", "Static"))
        self.checkBox_ctrl_grp_tgl_img_6.setText(_translate("MainWindow", "Group"))
        self.pushButton_ctrl_tgl_img_6.setText(_translate("MainWindow", "Toggle"))
        self.label_ctrl_frame1_img_6.setText(_translate("MainWindow", "Frame 1"))
        self.label_ctrl_frame2_img_6.setText(_translate("MainWindow", "Frame 2"))
        self.pushButton_tgl_group.setText(_translate("MainWindow", "Group Toggle"))
        self.groupBox_plots.setTitle(_translate("MainWindow", "Plots"))
        self.label_img_tminus.setText(_translate("MainWindow", "Image t-1"))
        self.label_img_t.setText(_translate("MainWindow", "Image t"))
        self.label_img_tplus.setText(_translate("MainWindow", "Image t+1"))
        self.label_disp.setText(_translate("MainWindow", "Disparity Prediction for Image t"))
        self.label_depth.setText(_translate("MainWindow", "Depth Prediction for Image t"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_depth_disp), _translate("MainWindow", "Depth and Disparity"))
        self.label_img_1.setText(_translate("MainWindow", "Image 1"))
        self.label_img_2.setText(_translate("MainWindow", "Image 2"))
        self.label_img_3.setText(_translate("MainWindow", "Image 3"))
        self.label_img_4.setText(_translate("MainWindow", "Image 4"))
        self.label_img_5.setText(_translate("MainWindow", "Image 5"))
        self.label_img_6.setText(_translate("MainWindow", "Image 6"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_warps), _translate("MainWindow", "Warps"))

